# This file is autogenerated. Do not edit this file.
# It may be replaced when you upgrade to new versions of watircraft.

require 'rubygems'

library = File.expand_path(File.dirname(__FILE__) + '/../../lib')
$LOAD_PATH.unshift library
require 'initialize'
require 'cucumber'

step_libs = Dir.chdir(library) {Dir["steps/*.rb"]}
step_libs.each {|f| require f}
