# This file is autogenerated. Do not edit this file.
# It may be replaced when you upgrade to new versions of watircraft.

require 'init/site_start'
require 'spec'
require 'mocha'

Spec::Runner.configure do |config|
  config.mock_with :mocha
  config.before(:all) do
    SITE.initialize_context!(self)
  end
  config.before(:each) do
    SITE.initialize_context!(self)
  end
end