# This file is autogenerated. Do not edit this file.
# It may be replaced when you upgrade to new versions of watircraft.

require 'rubygems'

$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../../lib/')
require 'init/spec_initialize'


