# This file is autogenerated.
# Do not edit this file. It will be automatically replaced when you 
# upgrade to newer versions of watircraft.

require 'site_start'
require 'spec'
require 'mocha'

Spec::Runner.configure do |config|
  config.mock_with :mocha
  config.before do
    SITE.initialize_context!(self)
  end
end