# This file is autogenerated.
# Do not edit this file. It will be automatically replaced when you 
# upgrade to newer versions of watircraft.

require 'spec'
require 'cucumber'
$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/..')
require 'site_start'

World do
  START
end
