# This file is autogenerated. Do not edit this file.
# It may be replaced when you upgrade to new versions of watircraft.

require 'spec'
require 'cucumber'

$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/..')
require 'init/site_start'

World do
  SITE
end
